# Generated by Django 5.0.2 on 2024-02-27 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ip", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WifiNetwork",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ssid", models.CharField(max_length=100)),
                ("password", models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="vlan",
            name="id",
        ),
        migrations.AlterField(
            model_name="vlan",
            name="vlan_id",
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
