# Generated by Django 5.0.2 on 2024-03-18 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ip", "0003_clientdevice"),
    ]

    operations = [
        migrations.CreateModel(
            name="IpRange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_address", models.GenericIPAddressField()),
                ("end_address", models.GenericIPAddressField()),
                ("num_addresses", models.PositiveIntegerField()),
                ("description", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
