# Generated by Django 5.0.2 on 2024-02-27 21:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ip", "0002_wifinetwork_remove_vlan_id_alter_vlan_vlan_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClientDevice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("mac_address", models.CharField(max_length=17, unique=True)),
                (
                    "ip_address",
                    models.GenericIPAddressField(blank=True, null=True, unique=True),
                ),
                (
                    "connection_type",
                    models.CharField(
                        choices=[("ethernet", "Ethernet"), ("wifi", "WiFi")],
                        max_length=10,
                    ),
                ),
                (
                    "vlan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="ip.vlan"
                    ),
                ),
                (
                    "wifi",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ip.wifinetwork",
                    ),
                ),
            ],
        ),
    ]
