# Generated by Django 5.0.2 on 2024-04-14 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Circuit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("current_rating", models.PositiveIntegerField()),
                (
                    "breaker_type",
                    models.CharField(
                        choices=[
                            ("fuse", "Fuse"),
                            ("mcb", "MCB"),
                            ("rcd", "RCD"),
                            ("rcbo", "RCBO"),
                            ("gfci", "GFCI"),
                        ],
                        max_length=10,
                    ),
                ),
                ("spd_protection", models.BooleanField()),
                ("wire_diameter", models.FloatField()),
                (
                    "circuit_type",
                    models.CharField(
                        choices=[
                            ("lighting", "Lighting"),
                            ("outlet", "Outlets"),
                            ("appliance", "Appliance"),
                            ("heating", "Heating"),
                            ("cooling", "Cooling"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
            ],
        ),
    ]
