# Generated by Django 5.0.2 on 2024-03-19 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("electric", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="circuit",
            name="circuit_type",
            field=models.CharField(
                choices=[
                    ("lighting", "Lighting"),
                    ("outlet", "Outlets"),
                    ("appliance", "Appliance"),
                    ("heating", "Heating"),
                    ("cooling", "Cooling"),
                ],
                max_length=20,
            ),
        ),
    ]
